from pinecone import Pinecone,Index
from typing import List
# import PyPDF2
# from langchain.document_loaders.pdf import PyPDFDirectoryLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain.schema.document import Document
# import pdf_reader_tool as pdf_reader_tool
import PDF_Context_Code.pdf_reader_tool as pdf_reader_tool

# Configuration
DATA_PATH = "/Data"
PINECONE_API_KEY = "pcsk_2HnqHd_MuZHH8s6PNsFc2w6cdGJm9xk8jhJt73WMWkEJW2cq996HsdmtrXsJJ1WQUXJh81"
PINECONE_ENV = "us-east-1"
INDEX_NAME = "nn"
PDF_PATH = "PDF_Context_Code/Data/Demo.pdf"

# Initialize Pinecone Serverless
def init_pinecone(api_key: str, environment: str, index_name: str):
    pc = Pinecone(api_key=api_key)
    return pc.Index(index_name)

index = init_pinecone(PINECONE_API_KEY, PINECONE_ENV, INDEX_NAME)

# Store text in Pinecone (Pinecone generates embeddings)
def store_in_pinecone(index, chunks, pdf_name: str):
    vectors = []
    for chunk in chunks:
        # Pinecone Serverless will generate embeddings from the text
        vectors.append({
            "_id": chunk['metadata']['chunk_id'],
            "text":chunk['content'],
            "Section": chunk['metadata']['section']
        })

    print(vectors[0])
    return vectors

def insert_records(PDF_PATH:str):
    # text_chunks = pdf_reader.generate_chunks(PDF_PATH)
    text_chunks = pdf_reader_tool.get_chunks(PDF_PATH)
        
    # Store in Pinecone (embeddings generated by Pinecone)
    print("Storing text in Pinecone (embeddings will be auto-generated)...")
    pdf_name = PDF_PATH.split('/')[-1].replace('.pdf', '')
    
    index.upsert_records("default",store_in_pinecone(index, text_chunks, pdf_name))
    
def check_pinecone_index_data() -> bool:
    try:
        # Get index stats
        stats = index.describe_index_stats()
        
        # Check total vector count
        total_vectors = stats.get('total_vector_count', 0)
        
        return total_vectors > 0
    
    except Exception as e:
        print(f"Error checking Pinecone index: {str(e)}")
        return False

def pdf_context_extractor(query):
    init_pinecone(PINECONE_API_KEY,PINECONE_ENV,INDEX_NAME)
    if(check_pinecone_index_data() == False):
        insert_records(PDF_PATH)
    try:
        results = index.search_records(
            namespace="default", 
            query={
                "inputs": {"text": query}, 
                "top_k": 5
            },
            fields=["category", "text"]
        )
        return results

    except Exception as e:
        print(f"An error occurred: {str(e)}")
